Update MarkerEditor.cs
VRLabs/Marker pull request #1
Opened 2022-05-30 05:20 UTC by GapVR

CheckRequirements(): Update to 256 bit (VRC ver 1201+).

2022-05-30 06:12 UTC, Cibbi requested changes

2022-05-30 06:12 UTC, Cibbi commented on Editor/MarkerEditor.cs
> +				if (descriptor.expressionParameters != null && descriptor.expressionParameters.CalcTotalCost() > (256 - bitCount))
It was an error on our side to hardcode the bits total cost here, it should not be hardcoded and use `VRCExpressionParameters.MAX_PARAMETER` instead

2022-05-30 06:12 UTC, Cibbi commented on Editor/MarkerEditor.cs
> +					warnings.Add("You don't have enough free memory in your avatar's Expression Parameters to generate. You need " + (256 - bitCount) + " or less bits of parameter memory utilized.");
Same as above

2022-06-01 07:02 UTC, oofdesu commented
going to close this pending an update from ksivl

2022-06-01 07:02 UTC, closed without merging